- name: "install_apache"
  apt:
    update_cache: yes
    name:
      - "apache2"
      - "libapache2-mod-fcgid"
      - "libapache2-mod-security2"
      - "libapache2-mod-evasive"
      - "openssl"
    state: latest
  notify:
    - set_apache_service

- name: "enable_apache_modules"
  apache2_module:
    name: "{{ item }}"
  with_items:
    - actions
    - alias
    - fcgid
    - headers
    - proxy_fcgi
    - ssl

- name: "set_virtual_host"
  template:
    src: templates/site.conf
    dest: /etc/apache2/sites-available/{{ VH_FILENAME }}.conf
  notify:
    - enable_site
    - reload_apache_service
    - add_static_dns_entry