- name: "install_php"
  apt:
    update_cache: yes
    name: 
      - php7.3 
      - php7.3-fpm 
      - php7.3-cli 
      - php7.3-common 
      - php7.3-curl 
      - php7.3-mbstring 
      - php7.3-mysql 
      - php7.3-xml 
      - php7.3-gd 
      - php7.3-exif
    state: latest